# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detec_image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detec_image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x64\x65tec_image.proto\"F\n\x05image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\"\"\n\x0b\x64\x65tecresult\x12\x13\n\x0bstrofresult\x18\x01 \x01(\t29\n\x12Getdetectionresult\x12#\n\tGetdetres\x12\x06.image\x1a\x0c.detecresult\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='image',
  full_name='image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='image.channel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='image.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=91,
)


_DETECRESULT = _descriptor.Descriptor(
  name='detecresult',
  full_name='detecresult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strofresult', full_name='detecresult.strofresult', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['image'] = _IMAGE
DESCRIPTOR.message_types_by_name['detecresult'] = _DETECRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'detec_image_pb2'
  # @@protoc_insertion_point(class_scope:image)
  ))
_sym_db.RegisterMessage(image)

detecresult = _reflection.GeneratedProtocolMessageType('detecresult', (_message.Message,), dict(
  DESCRIPTOR = _DETECRESULT,
  __module__ = 'detec_image_pb2'
  # @@protoc_insertion_point(class_scope:detecresult)
  ))
_sym_db.RegisterMessage(detecresult)



_GETDETECTIONRESULT = _descriptor.ServiceDescriptor(
  name='Getdetectionresult',
  full_name='Getdetectionresult',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='Getdetres',
    full_name='Getdetectionresult.Getdetres',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_DETECRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETDETECTIONRESULT)

DESCRIPTOR.services_by_name['Getdetectionresult'] = _GETDETECTIONRESULT

# @@protoc_insertion_point(module_scope)
