# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import detec_image_pb2 as detec__image__pb2


class GetdetectionresultStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Getdetres = channel.unary_unary(
        '/Getdetectionresult/Getdetres',
        request_serializer=detec__image__pb2.image.SerializeToString,
        response_deserializer=detec__image__pb2.detecresult.FromString,
        )


class GetdetectionresultServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Getdetres(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetdetectionresultServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Getdetres': grpc.unary_unary_rpc_method_handler(
          servicer.Getdetres,
          request_deserializer=detec__image__pb2.image.FromString,
          response_serializer=detec__image__pb2.detecresult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Getdetectionresult', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
